siteName: doublecool
productionUrl: https://poko-website-builder-78e.pages.dev/
languages:
  - code: fr
    name: fran√ßais
    customUrlPrefix:
      prefix: ''
    status: published
    isCmsDefault: false
    isWebsiteDefault: false
