siteName: doublecool
productionUrl: poko-website-builder-78e.pages.dev
languages:
  - code: fr
    name: fran√ßais
    customUrlPrefix: null
    status: published
    isCmsDefault: false
    isWebsiteDefault: false
